# Generated by Django 5.2.5 on 2025-08-25 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250)),
                ('counter', models.PositiveBigIntegerField(default=0)),
                ('order_id', models.PositiveIntegerField(db_index=True, default=0)),
                ('audio_url', models.URLField()),
                ('text', models.TextField(blank=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='content_api_app.page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250)),
                ('counter', models.PositiveBigIntegerField(default=0)),
                ('order_id', models.PositiveIntegerField(db_index=True, default=0)),
                ('video_url', models.URLField()),
                ('subtitles_url', models.URLField(blank=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='content_api_app.page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
