# Generated by Django 5.2.5 on 2025-08-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'ordering': ('order_id',)},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('order_id',)},
        ),
    ]
